name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubintu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build
        working-directory: ./java/src
        run: javac lab1/PrimeArray.java lab1/Main.java 
      -name: Test
        working-directory: ./java
        run: |
          javac -cp "./junit/junit-platform-console-standalone-1.9.0.jar" ./src/lab1/PrimeArray.java ./src/lab1/PrimeArrayTests.java
          java -jar ./junit/junit-platform-console-standalone-1.9.0.jar -cp "./src" --select-class lab1.Main